{"name": "test_add[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == '请输入数字'\n  +None\n  -'请输入数字'", "trace": "self = <test_calculator.TestCalc object at 0x03984770>, get_calc = <calculator.page.calculator.Calculator object at 0x0395FCB0>\nget_add_datas = ['', 5, '请输入数字']\n\n    @pytest.mark.run(order=0)\n    def test_add(self, get_calc, get_add_datas):\n        result = None\n        try:\n            # 调用add函数,返回的结果保存在result里面\n            result = get_calc.add(get_add_datas[0],get_add_datas[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_add_datas[2]\nE       AssertionError: assert None == '请输入数字'\nE         +None\nE         -'请输入数字'\n\ntest_calculator.py:26: AssertionError"}, "parameters": [{"name": "get_add_datas", "value": "['', 5, '请输入数字']"}], "start": 1613871860356, "stop": 1613871860357, "uuid": "f7192a49-c2a2-4901-892a-8bc676e65a32", "historyId": "99866defb12788d09dac54241e25d4c0", "testCaseId": "631576586691ad4a52ceb73d073b0e40", "fullName": "calculator.TestCase.test_calculator.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=0)"}, {"name": "parentSuite", "value": "calculator.TestCase"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-8M4A9CB"}, {"name": "thread", "value": "4312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "calculator.TestCase.test_calculator"}]}