{"name": "test_div[negative number]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0.5 == -3\n  +0.5\n  --3", "trace": "self = <test_calculator.TestCalc object at 0x03984BD0>, get_calc = <calculator.page.calculator.Calculator object at 0x0395FCB0>\nget_div_datas = [-1, -2, -3]\n\n    @pytest.mark.run(order=3)\n    def test_div(self, get_calc, get_div_datas):\n        result = None\n        try:\n            # 调用div函数,返回的结果保存在result里面\n            result = get_calc.div(get_div_datas[0],get_div_datas[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except ZeroDivisionError as e:\n            print(e)\n>       assert result == get_div_datas[2]\nE       assert 0.5 == -3\nE         +0.5\nE         --3\n\ntest_calculator.py:40: AssertionError"}, "parameters": [{"name": "get_div_datas", "value": "[-1, -2, -3]"}], "start": 1613871860587, "stop": 1613871860587, "uuid": "2e986b99-9e93-4ad0-9a78-0bddf955d7da", "historyId": "e08314776cb0506074de03a48da57a98", "testCaseId": "9323664d96830041be80d6c6726e9e46", "fullName": "calculator.TestCase.test_calculator.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "parentSuite", "value": "calculator.TestCase"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-8M4A9CB"}, {"name": "thread", "value": "4312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "calculator.TestCase.test_calculator"}]}